{
    'name': 'Objets IBATIX',
    'version': '19.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Gestion des objets IBATIX dans Odoo',
    'author': 'ibatix',
    'depends': ['product', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'views/mandataire_anah_views.xml',
        'views/mediateur_cee_views.xml',
        'views/delegataire_cee_views.xml',
        'views/cofrac_views.xml',
        'views/gestionnaire_reseau_views.xml',
        'views/matrice_precarite_views.xml',
        'views/auditeur_views.xml',
        'views/installateur_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
